# Generated by Django 3.0.6 on 2022-06-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_manual',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
